# Generated by Django 4.0.5 on 2022-07-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
